[project]
name = "chinese-railway-gtfs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "railgo-parser",
  "regex>=2026.9.29",
  "sqlalchemy>=2.1.4",
]

[project.scripts]
chinese-railway-gtfs = "chinese_railway_gtfs:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"

[tool.uv.sources]
railgo-parser = { git = "https://github.com/RailGoApps/RailGo-Parser.git" }
